---
title: "DynamicDocumentsNotes"
output: pdf_document
---

## Reproducible Research

### Literature

* RR was proposed by Jon Claerbout at Stanford Univ. 
  + "Final product of research is not only the paper itself, but also the 
  full computational environment used to produce the results in the paper 
  such as the code and data necessary for reproduction of the results and
  building upon the research" (5)
* At a technical level, RR is related to literate programming 
  + Donald Knuth -> integrate computer code with software documentation
  in one document

### Good and Bad Practices

* Manage all source files under the same directory and use relative paths
* Do not change working directory after the computing has started
* Compile documents in a clean R session
* Avoid commands that require human interaction
* Avoid environment variables for data analysis
* Attach *sessionInfo()* and instructions on how to compile the document


### Barriers

A non-exhaustive list of some practical barriers:

* Huge data sets
* Confidentiality of data
* Software version and configuration
* Competition


## Document Formats

* 3 key components of knitr package:
  1. a source parser
    + parses the source document and identifies computer code chunks as well 
    as inline code from the document
  2. a code evaluator
    + executes the code and returns results
    + independent of document format
  3. an output renderer
    + formats the results from computing in an appropriate format -> will be
    combined with original documentation

### Show/Hide Output
* We can show or hide different parts of the text output including the source code, 
  normal text output, warnings, messages, errors, and the whole chunk.
* *echo* (TRUE) whether to show the source code; it can also take a numeric vector
  to select which expressions to show in the output
    + echo = 1:3 selects the first 3 expressions
    + echo = -5 means do not show the 5th expression
* *results* ('markup') how to wrap up the normal text output that would have been
  printed in the R console if we had run the code in R
    + ('asis) write the raw output from R to the output document without any markups
    + ('hide') this option hides the normal text output
* *warning/error/message* (TRUE) whether to show warnings, errors, and messages
* *split* (FALSE) whether to redirect the chunk output to a separate file
* *include* (TRUE) wheter to include the chunk output in the document
* to completely stop knitr when errors occur:
```
opts_knit$set(stop_on_error = 2L)
```
  + **0L** do not stop on errors
  + **1L** when an error occurs, return the results up to this point and ignore the
    rest of code in the chunk but do not throw the error either
  + **2L** a full stop on errors


## Cache
The basic idea of caching is: a chunk will not be re-executed as long as it has not 
been modified since the last run, and old results will be directly loaded instead

* Lazy-loading essentially means that an object will not be loaded into memory unless
it is really used anywhere- only a "promise" is created which is usually fast and cheap
in terms of memory
  + when this promise is to be used for computation, the real object will be loaded 
    from a hard disk
  + useful for cache; sometimes we read a large object, cache it, then take a subset for
    analysis and this subset is cached; in the future, the initial object will not be
    loaded into R if our computation is only based on the object of its subset

* The path of cache files are determined by the chunk option cache.path 
  + By default, all cache files are created under a directory cache/ relative to the 
    working directory

* The cache is invalidated and purged on any changes to the code chunk
* Cache dependencies include manual and automatic (76)





    

