---
title: "Notes_09_22_15"
output: pdf_document
---

The training and test sets to build model- separate lifts
Random forests classification trees and nearest neighbor approaches

Method
build predictive models
need to be able to estimate error in real life situations- division into training set and test set
we have to be careful how it is separated- no single lift appears in both sets -> further than dr. white -> new lift 
in real life there will be different people, so this model will be worse for new people (error rate)


Can we predict how someone is performing a weight lift motion based on numeric info that instruments provide?

header-includes:
  \usepackage{setspace}
  \doublespacing
  
  
  Go back and make sure everything is reworded in my own words!! -> Use my bibliography!
  
  Make clear article title and authors go together
  
  General considerations of model making (test and train data sets)
  types of predictive models (RF is the main one, but I am interested in other simpler techniques k-NN)
  
  Make clear how GitHub Repo works
  
  
Thesis Goals:

  * Plan to have all research to be reproducible -> go to GitHub to get recipe to reproduce what I got
  * Build an honest predictive model- one to use in real life
  * This report is always publicly available on (https://github.com/esash77/WeightLifting/tree/master/Proposal)
  